### ISSUE TITLE
Publisher's logo size: structured data and design may conflict

### ISSUE THREAD

**Issue by Cupofbrain** [insideout10/wordlift-plugin#706] opened 2017-11-21 16:49 UTC
When you **select a logo** for your website's publisher, the logo itself is used as a **featured image**. 

According to Google's Developers Guide, the required size for logos is a rectangle 600*60.

> The logo should fit in a 60x600px rectangle., and either be exactly 60px high (preferred), or exactly 600px wide.
Source: https://developers.google.com/search/docs/data-types/articles

If you don't follow this simple rule, Google's Structured Data Testing Tool will highlight one error -- so that you really have no choice but using the mandatory size if you want your structured data to be clean. 

And here comes the conflict with the design of the entity page: the featured image frequently has a relevant role on the page, and 60x600px may not fit well as a featured image because it's very small. As you can imagine, 60px height is really small and the logo may result stretched on page.

**Comment by ziodave** [comment] 2018-05-26 09:13
Duplicate of #597. Closing.

**Closed by ziodave** 2018-05-26 09:13 UTC
