### ISSUE TITLE
Old articles appear in Vocabulary 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#662] opened 2017-10-16 16:32 UTC
On a customer website, old articles appear in the vocabulary. It seems that since WordLift does not set them up automatically as "article," they show up by default in the vocabulary. However, this does not happen with new articles.

![grabilla g11652](https://user-images.githubusercontent.com/26247261/31623587-29f9c8e6-b2a0-11e7-9261-c0d2292bb275.png)

To reproduce the issue: 
1. Install WordLift on a blog with preexisting articles 
2. Go into the vocabulary 
3. See that preexisting articles show up in the vocabulary because they have not been set up as "article."

**Comment by markkap** [comment] 2017-10-17 07:29
@ziodave it seems to be a problem with the upgrade process. we should not have any posts which are not articles in 3.15 this will break all queries, not just the admin..... unless there is something else going on as well.

**Comment by ziodave** [comment] 2017-10-17 07:41
@markkap I'll create a UT for this, I have a feeling we don't do enough UTs. Then we'll see how to handle it.

**Comment by ziodave** [comment] 2017-10-17 07:54
I really can't reproduce this one. The only guess, as it happened with another customer, is that the _Article_ taxonomy term isn't assign to existing posts, i.e. that the update terminates beforehand.

I guess this might be due to a large number of existing posts.

**Comment by ziodave** [comment] 2017-10-17 08:32
Manually deleting the term from a post shows the post in the Vocabulary.

**Comment by ziodave** [comment] 2017-10-17 09:52
I added the following fragment to queries for entities that specify slug NOT IN 'article':

```
		'relation' => 'AND',
		array(
			'taxonomy' => Wordlift_Entity_Types_Taxonomy_Service::TAXONOMY_NAME,
			'operator' => 'EXISTS',
		),
```

**Closed** 2017-10-26 09:02 UTC
Labels: status: resolved, type: bug
