### ISSUE TITLE
Annotation are not saved as </span> moves to the next line 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#432] opened 2017-01-04 17:47 UTC
Here is the case (the text can be found here http://www.catalogo.beniculturali.it/sigecSSU_FE/dettaglioScheda.action?keycode=ICCD4644223&titoloScheda=dipinto&valoreTitoloSchedaHome=true&sbiancaBreadCrumbs=yes): 

![image](https://cloud.githubusercontent.com/assets/837037/21652518/2d7e736e-d2ad-11e6-822e-0713be0e3385.png)

This is what happens
![image](https://cloud.githubusercontent.com/assets/837037/21652538/426748aa-d2ad-11e6-9feb-eb8b36c931b8.png)

Here is the code

```
<span id="urn:enhancement-9aceedb8-41a3-cdc6-6962-1c11a2222c12" class="textannotation disambiguated wl-person" itemid="http://data.wordlift.it/testwordlift/entity/guercino"><span id="urn:enhancement-73cadf3c-43d1-1777-5c84-88b3d2b0b6f5" class="textannotation disambiguated wl-person" itemid="http://data.wordlift.it/testwordlift/entity/guercino">Guercino
</span> </span>`
```

**Comment by ziodave** [comment] 2017-01-04 17:48
Most probably related to https://github.com/insideout10/wordlift-plugin/issues/399

**Comment by Stoyan0v** [comment] 2017-09-19 16:11
I've spent some time on this and it's working everywhere except on WordPress installs.
I've change the pattern to match everything except only spaces and new lines (https://github.com/insideout10/wordlift-plugin/commit/a8e7bdb3165d9ab2d6dd66cbab9ab5f333d6e8b4)
Here is an example: https://regex101.com/r/hGwJdM/1

The possible reason that this pattern doesn't work is "double line spacing in WordPress". I didn't find any solution so far, how to match this spacing.

@ziodave Do you have any idea how to match this double line spacing?

**Comment by ziodave** [comment] 2017-10-13 15:42
This appears to be a duplicate of #399 .

**Comment by ziodave** [comment] 2018-05-28 15:54
This is fixed with the new regex. Feel free to reopen.

**Closed by ziodave** 2018-05-28 15:54 UTC
Labels: severity: high, status: in progress, type: bug
