### ISSUE TITLE
Vocabulary is NOT accessible from the Dashboard if you're NOT Administrator

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#94] opened 2015-09-03 14:26 UTC
Editors and Authors shall be able to work on the WordLift vocabulary and this means that the Vocabulary button shall be made accessible.

**Comment by ziodave** [comment] 2015-11-09 21:03
@cyberandy I can't reproduce this one. Editors can see and edit the vocabulary. We can this one together and then eventually close it.

**Comment by ziodave** [comment] 2015-11-20 22:29
closing since it cannot be reproduced.

**Closed by ziodave** 2015-11-20 22:29 UTC
Labels: bug, cantreproduce, low
