### ISSUE TITLE
Entity Annotation Loop 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#350] opened 2016-09-26 15:56 UTC
The case is the following: 
- create an entity from scratch that is not automatically detected by the analysis _yvon chouinard_ (it was not found in the beginning on the latest blog post on the IO10 EN blog) 
- when the entity is created from the widget click on the proposed DBpedia link (this correctly points to the entity on _yvon chouinard_ DBpedia)
- save the article in draft 
- go to the entity _yvon chouinard_ and there in the description where the name _yvon chouinard_ appears WordLift proposes a new entity fetched from DBpedia that reproposes the entity itself

This should not happen - If I am working on an entity (while this entity might be in draft) I don't expect to see the entity itself in the results.

**Comment by ziodave** [comment] 2016-09-26 16:12
I think it's a duplicate of #345 ?

**Comment by cyberandy** [comment] 2016-10-06 19:07
It's slightly different. #345 is simple and in previous releases we didn't show the entity as result of the analysis of the description of the same entity. This case here is different and has to do with the process of creating a new entity from the vocabulary rather than from the WordLift widget. When creating it from the vocabulary WordLift doesn't look for the sameAs links and therefore this issue occurs.

**Comment by ziodave** [comment] 2016-10-10 20:28
WLP could send the URL of the current entity to WLS in order for WLS to exclude the current entity from the results.

**Comment by ziodave** [comment] 2016-10-10 20:29
However this is not a bug (we never had this requirement) and I believe it's low priority since you can just avoid selecting the entity itself from the results.

**Closed** 2017-02-07 16:15 UTC
Labels: enhancement, low, resolved
