### ISSUE TITLE
Entity in draft are not properly re-used and a new entity is created instead 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#277] opened 2016-02-29 11:58 UTC
The use case is the following: 

- an entity is saved in the vocabulary as **draft**
- when annotating an article the entity is detected as _internal_ (the bookmark icon is displayed)
- when saving the article with the entity rather than bringing the entity from _draft_ to _published_ a new entity is created. 

This has been spotted on the camminandocon.org website. 

It would be nice to inform the user that an entity in draft will be published as result of the analysis of a blog post. For sure duplicating the entity with a new entity is not the expected behaviour.

**Comment by mcolacino** [comment] 2016-02-29 13:20
@cyberandy Can you provide more details about it? draft entities should not be present on RL (meaning they should not be returned by the analysis in any case)... Maybe a further investigation on involved entities is required here.

**Comment by cyberandy** [comment] 2016-02-29 14:09
Sure, the starting blog post is an entity and it is here:
/entity/monte-navegna/ <http://camminandocon.org/entity/monte-navegna/>.
The new entity is Gran Sasso
<http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl049/entity/gran_sasso>
and
corresponds to /post.php?post=726
<http://camminandocon.org/wp-admin/post.php?post=726&action=edit> in WP and
replaces /post.php?post=1129 that has been now deleted.

If I check the following over SPARQL

``SELECT * WHERE {
  ?subject ?property ?object
             filter regex(str(?subject), "gran")
}
LIMIT 10``

I receive one entity only
<http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl049/entity/gran_sasso>.
My assumption is that we create the entity on Redlink when it is in `draft`
(and it makes sense) but we duplicate the entity when saving the post for
some reason but I didn't replicate it yet.

**Comment by mcolacino** [comment] 2016-02-29 18:09
Here the problem is that while it exists an entity called *Gran Sasso* in *draft*, the analysis returns the dbpedia resource http://lod.openlinksw.com/describe/?url=http%3A%2F%2Fdbpedia.org%2Fresource%2FGran_Sasso_d%27Italia
New entity is created becouse the original one has no reference to the dbpedia one. The workaround here is to be sure internal entities are **published** in order to use / see them in the disambiguation ... As enhancement we should allow editor to link internal to entities to the LOD not only trough the disambiguation widget, but also trough the vocabulary.

**Comment by mcolacino** [comment] 2016-02-29 18:10
Please also notice that in 3.4 if both entities are published there is a conflict on RL side. This situation is fixed in 3.5

**Closed** 2016-08-25 14:26 UTC
Labels: bug, medium, wontfix
