### ISSUE TITLE
Navigator widget doesn't show at the end of the article unless it is also in the middle.

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#336] opened 2016-09-02 08:57 UTC
While working on this article, 
http://camminandocon.org/2016/07/comunicando-con/
I noticed that the navigator widget does not show at the end of the article:

![end no navigator](https://cloud.githubusercontent.com/assets/18528457/18198479/92039f7a-70fc-11e6-8958-1cc90b14dec9.png)

![end nav](https://cloud.githubusercontent.com/assets/18528457/18198480/9209dc00-70fc-11e6-8a88-6de414d0de48.png)

unless I also insert it in the middle of the article:

![middle nav](https://cloud.githubusercontent.com/assets/18528457/18198566/eae264be-70fc-11e6-81fc-9d642319a6a7.png)
![middle](https://cloud.githubusercontent.com/assets/18528457/18198571/ec6c35b2-70fc-11e6-83e6-12fe7dd53c35.png)
![end nav](https://cloud.githubusercontent.com/assets/18528457/18198573/ee543ee2-70fc-11e6-94e7-93dfc807f68c.png)
![end w nav](https://cloud.githubusercontent.com/assets/18528457/18198574/efca4244-70fc-11e6-9645-835b3b718eb6.png)

It works just fine when it's just in the middle of the article:
![middle nav](https://cloud.githubusercontent.com/assets/18528457/18198587/f7ec1c68-70fc-11e6-9310-41d363fd8ff6.png)
![middle](https://cloud.githubusercontent.com/assets/18528457/18198591/f936a9b2-70fc-11e6-8ede-538168b1fabc.png)

**Comment by ziodave** [comment] 2016-09-03 07:36
Changed from _high_ to _medium_ since it's not critical to the web site workflow.

**Comment by ziodave** [comment] 2016-09-03 08:17
Can be reproduced also with WordPress' standard themes (e.g. Sixteen).

**Comment by ziodave** [comment] 2016-09-03 11:58
The issue is related to `wl_chord`:

* this works: ```[wl_navigator][wl_chord]```
* this doesn't work: ```[wl_chord][wl_navigator]```

**Comment by ziodave** [comment] 2016-09-03 12:09
The `wl_chord` (and also the `wl_timeline`) loads the `wordlift-ui` javascript code but doesn't set correctly the dependencies.

It might be better to create one wordlift-ui js with all the dependencies.

For the time being I am gathering all the required code to load the wordlift-ui in an abstract class which shortcodes can extend and that will set correctly the dependencies.

**Comment by ziodave** [comment] 2016-09-03 12:30
@novedavi we need to carefully test this fix, let's have a chat, we need to test the 4 shortcodes:

* wl_chord,
* wl_geomap,
* wl_navigator,
* wl_timeline.

**Comment by ziodave** [comment] 2016-09-07 07:48
merged in master.

**Comment by ziodave** [comment] 2016-09-08 05:34
Published with 3.5.4

**Closed by ziodave** 2016-09-08 05:34 UTC
Labels: bug, medium, resolved
