### ISSUE TITLE
Entity annotation not working for entity "Tao della sessualità"

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#226] opened 2016-01-06 18:14 UTC
The case is the following: 

- this is the entity being enriched http://taoroma.it/entity/sessualita/
- in the first place WordLift correctly detects the newly created entity ("Tao della Sessualità" - http://taoroma.it/entity/tao-della-sessualita/) 
![image](https://cloud.githubusercontent.com/assets/837037/12150253/120a22e0-b4a9-11e5-9fbd-611980fca4dc.png)
- after choosing the entity "Tao della Sessualità" and saving the entity page ... **the annotation mysteriously disappears**

The entity "Tao della Sessualità" has an alternative label "sessualità taoista" and the entity "Tao" also exists in the user's vocabulary (this might interfere).

**Comment by mcolacino** [comment] 2016-01-06 22:51
@cyberandy could you provide / ask for the screenshot from the browser console?

**Comment by cyberandy** [comment] 2016-01-07 09:11
- After removing the entity from the text and adding it again - this is what happened: 
![image](https://cloud.githubusercontent.com/assets/837037/12166439/4a9ce43a-b526-11e5-9f67-481fc268e5f7.png)

- After clicking on the newly created annotation for "Tao della Sessualità" - this what happened: 
![image](https://cloud.githubusercontent.com/assets/837037/12166449/5eb6e2b8-b526-11e5-9957-1f2fb604eb44.png) 

- After selecting the entity from the Widget on the left - this is what happened: 
![image](https://cloud.githubusercontent.com/assets/837037/12166481/8c3260dc-b526-11e5-99d3-e0e905d0bc54.png)
![image](https://cloud.githubusercontent.com/assets/837037/12166490/96b2f97c-b526-11e5-92ac-c490ccb5c9ce.png) 

- After updating the post again - this is what happened: 
![image](https://cloud.githubusercontent.com/assets/837037/12166525/d15bb80c-b526-11e5-9373-5952a5de7e2e.png)

**Comment by mcolacino** [comment] 2016-01-07 21:07
**The annotation *disappears* becouse is not available neither in local storage nor in analysis results**.
From the following screenshot you can further see that **WLS returns an inconsistent annotation with no entity matches** in this case and this needs to be investigated on WLS / Redlink side
![schermata 2016-01-07 alle 21 50 55](https://cloud.githubusercontent.com/assets/1022181/12182669/f0a33c36-b589-11e5-8ef4-48919156adbd.png)
Another important thing is that the *broken annotation* is related to 
http://taoroma.it/entity/alchimia-interiore/ instead of http://taoroma.it/entity/tao-della-sessualita/ as expected. Please notice that http://taoroma.it/entity/tao-della-sessualita/ is *sameAs* of http://taoroma.it/entity/alchimia-interiore/ and both entities share the same secondary label "sessualità taoista". **This cross reference between entities can be the root couse of the annotation inconsistency and needs to be further investigated**
![schermata 2016-01-07 alle 21 45 58](https://cloud.githubusercontent.com/assets/1022181/12182703/26047d5e-b58a-11e5-9765-eb14b5db1151.png)

**Comment by cyberandy** [comment] 2016-01-07 21:21
All right - so we shall remove the *sameAs* with
http://taoroma.it/entity/alchimia-interiore/ as well as the secondary label
"sessualità taoista" for "alchimia interiore" and do one more test.


*Andrea Volpini*


*InsideOut10* <http://blog.insideout.io>
[image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2F%23!%2Fcyberandy&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fvolpini&sn=>
 [image: about.me]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fabout.me%2Fandreavolpini&sn=>
 [image: Tumblr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fblog.insideout.io&sn=> [image:
Blog RSS]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fandrea.volpini.com&sn=> [image:
Google Plus Page]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fplus.google.com%2F113000363475040285402%2Fposts&sn=>
 [image: SlideShare]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fslideshare.net%2Fcyberandy%2F&sn=>
 [image: Flickr]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fcyberandy%2F&sn=>


On Thu, Jan 7, 2016 at 10:07 PM, Marcello Colacino <notifications@github.com

**Comment by mcolacino** [comment] 2016-01-07 22:50
@cyberandy this could be a test. Anyway we have more elements to try to reproduce the bug. 
Furhter I also noticed that there is a duplicated entity for "Alchimia interiore"
http://taoroma.it/entity/alchimia-interiore-2/

**Comment by mcolacino** [comment] 2016-01-09 14:45
@cyberandy I finally reproduced the bug and I confirm is due to cross between internal entities - aka http://taoroma.it/entity/tao-della-sessualita/ is *sameAs* of http://taoroma.it/entity/alchimia-interiore/

**Comment by mcolacino** [comment] 2016-01-09 15:31
This issue is better defined now in #237. I Close this one.

**Closed by mcolacino** 2016-01-09 15:31 UTC
Labels: bug, medium
