### ISSUE TITLE
Entities from the internal vocabulary are not properly detected from the analysis

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#306] opened 2016-05-19 16:50 UTC
The case is the following. The entity `Perineo` exists in the user's vocabulary and has been [published on data.wordlift.it](http://data.wordlift.it/wl034/entity/perineo). When mentioned in the description of another entity the entity `Perineo` is detected from the analysis but it is linked to dbpedia and not to the user's vocabulary.
![image](https://cloud.githubusercontent.com/assets/837037/15401999/49cc96e2-1df2-11e6-977a-f53f23a80f8b.png)

This bug needs to be fixed urgently and has been spotted also by other users.

**Comment by mcolacino** [comment] 2016-05-19 17:20
Here is another example
![schermata 2016-05-19 alle 19 17 06](https://cloud.githubusercontent.com/assets/1022181/15402843/61b9cc4e-1df6-11e6-8448-57d7c4236668.png)

**Notice that if we add a dot after "Roma" results are different, and internal entities are properly returned as expected:

![schermata 2016-05-19 alle 19 19 18](https://cloud.githubusercontent.com/assets/1022181/15402878/9e5a3210-1df6-11e6-810d-dee1d5102e7a.png)

**This issue need to be escalated to RedLink**

**Comment by ziodave** [comment] 2016-08-25 15:10
I was able to reproduce it here: http://test.wordlift.it/wp-admin/post.php?post=4303&action=edit

Just refresh the page, sometime 'Appartamento9' is found sometime is not. The response from RL is different, I am attaching the responses' logs.

[appartamento9_found.txt](https://github.com/insideout10/wordlift-plugin/files/437359/appartamento9_found.txt)
[appartamento9_not_found.txt](https://github.com/insideout10/wordlift-plugin/files/437358/appartamento9_not_found.txt)

**Comment by cyberandy** [comment] 2016-09-08 13:10
Here is another case where entities from the local vocabulary are not detected from the analysis: 

In this blog post here: http://taoroma.it/wp-admin/post.php?post=4046&action=edit the entity **mano** is properly detected but rather than being derived from the local vocabulary (where the [entity is already present](http://taoroma.it/entity/mano/)) it comes from DBPedia. See below the _cloud_ icon being displayed in the widget. This occurs before choosing the entity and saving the post. 

![image](https://cloud.githubusercontent.com/assets/837037/18350063/65927416-75d4-11e6-8eee-29cae26971c7.png)

Once the entity has been chosen the match is properly done with the entity in the vocabulary, the icon becomes local storage and the description (displayed in the widget) is  derived from the vocabulary.

**Comment by cyberandy** [comment] 2016-09-08 13:16
Another example is detailed in #326

**Comment by ziodave** [comment] 2016-10-10 20:31
I am closing this one as it's not directly related to WL.

**Comment by wikier** [comment] 2016-12-01 09:36
The problem is that short text get identified as {{it, en}}. So there are three ways to get the issue solved:

1. Submit a longer text to lower the Italian
2. Define a label for the entity with no language tag (so a default label for any language)
3. Submit the content language if known (Header: {{Content-Language: en}})

**Comment by ziodave** [comment] 2016-12-01 09:37
The 3rd option is great, since the user selects the web site language.

**Comment by cyberandy** [comment] 2016-12-27 18:03
![image](https://cloud.githubusercontent.com/assets/837037/21505381/0d552df4-cc67-11e6-86a2-88a1434d952e.png)

Perineo is now detected and comes from the user's vocabulary.

**Comment by ziodave** [comment] 2016-12-28 07:17
> at the same time local entities like vaso di concezione still are not properly detected (i.e. here is another entity http://taoroma.it/entity/milza/)

We should open a new issue for this as it seems outside the scope of this one.

**Closed** 2016-12-29 08:10 UTC
Labels: bug, high, resolved
