### ISSUE TITLE
Finalize backend widget accordion 

### ISSUE THREAD

**Issue by wanbinkimoon** [insideout10/wordlift-plugin#388] opened 2016-11-04 11:12 UTC
This issue has 2 minor topics: 
  1. Arrows need to reverse if the tab is open 
![screen shot 2016-11-04 at 12 11 23](https://cloud.githubusercontent.com/assets/10087639/20003623/d842afa0-a287-11e6-90b4-e1ae78aef3d7.png)
  2. Empty section of the accordion needs to be hidden

**Comment by ziodave** [comment] 2017-02-02 15:14
Let's review this point as we replace the WordLift Edit Widget (metabox) with React components.

**Comment by ziodave** [comment] 2017-10-13 15:40
Duplicate of #387 ?

**Closed** 2022-10-12 02:07 UTC
Labels: wontfix, status: needs ux
