### ISSUE TITLE
Incompatibility with WPBakery Visual Composer 4.6

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#100] opened 2015-09-17 09:26 UTC
When editing a page using the Visual Composer WordLift messes up the text being previously added with the Visual Editor.

![image](https://cloud.githubusercontent.com/assets/837037/9929635/5243e12a-5d2e-11e5-9186-40b2d7fc2f5b.png)

Our usual workflow is as follow: 

- we start creating website using the Visual Composer 
- we install WordLift
- when we need to update a text on a page that is using the Visual Composer the content is messed up by WordLift and we need to de-activate WordLift, make the required changes in Visual Composer, save the page and than re-activate WordLift

A quick hotfix here is to **make sure the analysis only starts when the standard visual editor is being used** >> else WordLift (as it occurs when editing content using the Text editor of WordPress) shall not start.

**Comment by ziodave** [comment] 2015-11-09 21:08
Since this requires working on the client side, we need to postpone it after 3.1, i.e. when the merged repo goes to master.

**Comment by ziodave** [comment] 2015-11-22 08:03
@cyberandy can we review this together? maybe you're using an old version of WPBakery, I wasn't able to reproduce with WPBakery 4.8.1 and "classic mode" editing.

**Comment by ziodave** [comment] 2015-12-06 18:23
@cyberandy will reopen if can be reproduced.

**Closed by ziodave** 2015-12-06 18:23 UTC
Labels: bug, cantreproduce, low

**Comment by cyberandy** [comment] 2016-03-29 16:27
I've checked here that is _in theory_ possible to work with WordLift and the WPBakery Visual Composer. The workflow is as follows: 

1. compose the page using the Visual Composer
2. switch to classic mode 

![image](https://cloud.githubusercontent.com/assets/837037/14115478/79855cb4-f5db-11e5-8b8d-4e3573661bfe.png)

3. annotate the text with WordLift, eventually create new entities
4. publish 
5. if needed keep using the Visual Composer unless you add other textual contents to the page

Now having said so - there is a new enhancement to be made that is to avoid annotating all the shortcodes that the Visual Composer generates. I will create an enhancement for this one.
