### ISSUE TITLE
Duplicate entities appeared on the same site

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#506] opened 2017-03-29 09:41 UTC
Here is the case - two entities appeared on the geospatialworld website: 

- https://www.geospatialworld.net/entity/ordnance-survey%EF%BB%BF-international/
- https://www.geospatialworld.net/entity/ordnance-survey-international/ 

%EF%BB%BF gets in the URL after viewing the entity in the browser ("View Entity" from the WordPress back-end), copying the URL and pasting it in another text editor. 

As you can see from the images below the URL in the browser is the same but the content is actually different (in fact in the [second image](https://www.geospatialworld.net/entity/ordnance-survey-international/), corresponding to the second link  _Ordnance Survey_  is annotated by WordLift). 

![image](https://cloud.githubusercontent.com/assets/837037/24447965/fad43fb8-1472-11e7-888f-dc68692f1245.png)
![image](https://cloud.githubusercontent.com/assets/837037/24448026/270fc7d2-1473-11e7-8790-2f461211b8db.png)

Here is how it happened: 

1. while editing the article https://www.geospatialworld.net/article/digital-mapping-sustainable-development the entity was first created from the WordLift edit widget
2. while annotating the article a second entity was created for https://www.geospatialworld.net/entity/peter-hedlund/ 
3. while annotating the entity for Peter Hedlund _ordnance survey international_ was detected from the analysis and most probably the second entity was created

**Comment by ziodave** [comment] 2017-03-29 09:48
`%EF%BB%BF` is a UTF-8 sequence character. Most likely, the title of (1) was copy and pasted from an editor.

This is not a bug in WordLift.

See also:
 * [Wordpress shows /%EF%BB%BF/ in URL for template page](http://stackoverflow.com/questions/36307375/wordpress-shows-efbbbf-in-url-for-template-page)
 * [PHP and UTF-8 BOM (Or, why do my webpages start with ï»¿ )](https://alastaira.wordpress.com/2011/06/07/php-and-utf-8-bom-or-why-do-my-webpages-start-with/)

**Comment by ziodave** [comment] 2017-04-05 15:09
It appears the key has been used on more than one site. I am closing this one.

**Closed by ziodave** 2017-04-05 15:09 UTC
Labels: bug, high
