### ISSUE TITLE
Creating a Tag-Like Widget for articles

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#355] opened 2016-09-29 13:55 UTC
As of today we provide three means of content discovery for the user: _Navigator_, _Faceted Search_ and _Chord_. 

Following the initial request of a user we shall considering adding a simple front-end widget **to expose all the entities of an article as if they were tags** (eventually this same widget could be used site-wide in the side navigation bar). 

While for the first release it would be enough to display only entities directly correlated to an article - in future releases we could provide (_as done with the chord_) a way to get deeper in the archive:
1. _show me all entities of this article_ > 
2. _show me all entities of this article and all the entities connected with these entities_ > 
3. _show me all entities of this article and all entities connected with other articles that share at least 1 or 2 entities with this article_

![image](https://cloud.githubusercontent.com/assets/837037/18956815/190a0494-865d-11e6-9d56-42ba8a8ffe2c.png)

**Comment by markkap** [comment] 2017-02-03 04:21
Per discussion,we will start with a sort of duplicate of the tag cloud widget which will use the same html structure of the tag cloud widget and the same classes, in order to have a default styling by the theme and add to it a WordLift specific class to enable themers to add specific styling to it.

The widget will display only on post and entity pages and will display the entities relevant to that specific post and entity.

**Comment by markkap** [comment] 2017-02-22 15:45
@cyberandy I started to dig into it, and seems like if we want to have a "tag cloud" like widget, we need some definition of weight, which might be something like which entity is more connected I guess or some other criteria.

The other option is to go more into the direction of "recent posts" type of widgets. I guess it depends what is the default styling we want it to be assigned by the themes.

**Comment by cyberandy** [comment] 2017-02-22 17:07
The best option would be to define some sort of `entity relatedness` by combining: 

- # of connections that an entity has with articles
- # of connections the an entity has with other entities

Both of these parameters can also be used in the entity rating algorithm (see #433).
Would that work for you in this case?

**Comment by markkap** [comment] 2017-02-23 05:01
sure, will ask @ziodave for pointers where to get the info

**Comment by ziodave** [comment] 2017-02-26 14:47
@markkap here are the two calls to calculate number of connections...

* ...with entities: `wl_core_get_related_entity_ids( $id, array( 'status' => 'publish' ) )`,
* ...with posts: `wl_core_get_related_posts( $id, array( 'status' => 'publish' ) )`.

**Comment by markkap** [comment] 2017-02-27 15:52
The commit is very simple, lets you just configure the title of the widget. Tested with 2017 theme and looks ok, but should be tested with something that has more entities and content.

**Comment by ziodave** [comment] 2017-02-28 16:50
Still open:

- [ ] Unit Tests,
- [ ] Texts/Translations (we can review them during QA).

**Closed** 2017-03-16 15:55 UTC
Labels: enhancement, medium, merged, resolved
